Logbook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('log.urls')),
    path('admin/', admin.site.urls),
]

log/urls.py
from django.urls import path
from . import views

app_name = "log"


urlpatterns = [
    path('', views.log, name="log"),
    path('log/', views.log, name="log"),
]

accounts/models.py
from django.db import models

# Create your models here.

log/models.py
from django.db import models
from django import forms

# Create your models here.

class Log(models.Model):
    day = models.CharField(max_length=100)
    activities = models.CharField(max_length=300)
    plans = models.CharField(max_length=300)

    def __str__(self):
        return self.activities

log/forms.py
from django import forms
from .models import Log
from django.forms import ModelForm, Textarea

class LogModelForm(ModelForm):
    class Meta:
        model = Log
        fields = ['day', 'activities', 'plans']
        widgets = {
         'activities': Textarea(),
         'plans': Textarea()
        }

accounts/views.py
from django.shortcuts import render

# Create your views here.

log/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .forms import LogModelForm
from log.models import Log



def log(request):
    if request.method == "POST":
        form = LogModelForm(request.POST)
        if form.is_valid():
            data = form.save()
            print(data)
            return HttpResponseRedirect(reverse('log:log'))
    
    else:
        form = LogModelForm()
    
    return render(request, 'log.html', {'logform': form})

log/templates/log.html
<html>
    <head>
        {% load static %}
        <link href="{% static 'log.css' %}" rel="stylesheet">
    </head>
    <body>
        <header>
            <a class='header__brand'>
                <img src="#" alt="img">
                <h3 class="header__brand--h3">logbook</h3>
            </a>
            <ul class="header__ul">
                <li class="header__li">
                    <a class="header__li--a" href="#">Logout</a>
                </li>
            </ul>
        </header>

        <main>
            <form action="{% url 'log:log' %}" method="POST">
                {% csrf_token %}
                <div class="form__logwork">
                    <label for="id_activities">Today's Activities </label>
                    {{ logform.activities }}
                    <label for="id_plans">Plans for Tomorrow</label>
                    {{ logform.plans }}
                    <input id="logwork__form-submit" type="submit" value="COMMIT ENTRY">
                </div>
                <div class="form__calendar">           
                    {{ logform.day }}
                </div>
</form>
        </main>
        <footer>
            <ul class="footer__ul">
                <li class="footer__ul--li"><a href="#"><strong>contact us</strong></a></li>
                <li class="footer__ul--li"><a href="#">+256 752 633 239</a></li>
                <li class="footer__ul--li"><a href="#">gssenyonjo@gmail.com</a></li>
            </ul>
        </footer>
    </body>
</html>